In [1]:
#pip install numpy

#anaconda -> conda install numpy
#numpy


In [3]:
#importing numpy
import numpy as np

In [3]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape

(5,)

In [9]:
#multidimensional array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,5,6,8]

arr = np.array([my_lst1, my_lst2, my_lst3])

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 6, 8]])

In [11]:
arr.shape

(3, 5)

In [17]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 5, 6, 8]])

In [18]:
arr.shape

(3, 5)

In [19]:
#indexing


In [40]:
#accesing the array element
arr = np.array([1,2,3,4,5,6,7,8,9])

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[3]

4

In [24]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,5,6,8]
arr = np.array([my_lst1, my_lst2, my_lst3])

In [25]:
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 6, 8]])

In [26]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 6, 8]])

In [27]:
arr[1,2]

4

In [28]:
arr[0:1,0:1]

array([[1]])

In [29]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [31]:
arr[1:,3:]

array([[5, 6],
       [6, 8]])

In [32]:
arr[1:,2:4]

array([[4, 5],
       [5, 6]])

In [33]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [36]:
arr = np.arange(0,10,step=2)

In [37]:
arr

array([0, 2, 4, 6, 8])

In [39]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [46]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [44]:
arr1 = arr
arr1[3:]=500

In [45]:
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [47]:
print(arr)

[  1   2   3 500 500 500 500 500 500]


In [48]:
arr1 = arr.copy()


In [49]:
print(arr)

[  1   2   3 500 500 500 500 500 500]


In [50]:
arr1[3:]=1000
print(arr1)

[   1    2    3 1000 1000 1000 1000 1000 1000]


In [51]:
val = 2
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [52]:
arr*2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [53]:
arr/2

array([  0.5,   1. ,   1.5, 250. , 250. , 250. , 250. , 250. , 250. ])

In [54]:
arr%2

array([1, 0, 1, 0, 0, 0, 0, 0, 0])

In [55]:
arr+100

array([101, 102, 103, 600, 600, 600, 600, 600, 600])

In [56]:
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [57]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [58]:
arr[arr<20]

array([1, 2, 3])

In [59]:
np.ones(4)

array([1., 1., 1., 1.])

In [60]:
np.ones((2,5),dtype =int)
#two rows and 5 col of ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [68]:
#random distribution
np.random.rand(5,5)

array([[0.51664222, 0.50434313, 0.61452602, 0.44336184, 0.85786822],
       [0.05316072, 0.43625461, 0.06781426, 0.89979073, 0.77279681],
       [0.07530974, 0.46327257, 0.58815401, 0.56880643, 0.40346843],
       [0.37703251, 0.72847346, 0.43396913, 0.11117976, 0.47647319],
       [0.221295  , 0.0582119 , 0.273297  , 0.52061836, 0.27114634]])

In [74]:
np.random.randint(0,100,20).reshape(5,4)

array([[55, 19, 77, 17],
       [53, 69, 93, 82],
       [53, 56, 34, 79],
       [36, 97, 51, 24],
       [79, 81, 92, 54]])

In [1]:
#pandas
import pandas as pd
import numpy as np

In [83]:
#playing with data frame

df = pd.DataFrame(np.arange(0,20).reshape(5,4),index = ['Row1','Row2','Row3','Row4','Row5'],columns = ["Column1","Column2","Column3","Column4"])
                                                        
                                                        

In [84]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [85]:
df.to_csv('Test1.csv')
#make a csv file 

In [88]:
#accessing the elements
# 1 -> .loc(row index only) 2->> .iloc(index location)-(both row and column index)
type(df.loc['Row1'])


pandas.core.series.Series

In [93]:
type(df.iloc[:,:])

pandas.core.frame.DataFrame

In [94]:
df.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [95]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [98]:
#convert data frame to arrays
df.iloc[:,:].values.shape

(5, 4)

In [100]:
df['Column1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Column1, dtype: int64

In [101]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [102]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [105]:
df[['Column3','Column4']]

Column3  Column4
Row1        2        3
Row2        6        7
Row3       10       11
Row4       14       15
Row5       18       19

In [117]:
df = pd.read_csv('mercedesbenz.csv')

In [118]:
df

model  year  price transmission  mileage fuelType  tax   mpg  \
0             SLK  2005   5200    Automatic    63000   Petrol  325  32.1   
1         S Class  2017  34948    Automatic    27000   Hybrid   20  61.4   
2        SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0   
3         G Class  2016  61948    Automatic    16000   Petrol  325  30.4   
4         G Class  2016  73948    Automatic     4000   Petrol  325  30.1   
...           ...   ...    ...          ...      ...      ...  ...   ...   
13114     C Class  2020  35999    Automatic      500   Diesel  145  55.4   
13115     B Class  2020  24699    Automatic     2500   Diesel  145  55.4   
13116   GLC Class  2019  30999    Automatic    11612   Diesel  145  41.5   
13117   CLS Class  2019  37990    Automatic     2426   Diesel  145  45.6   
13118     S Class  2019  54999    Automatic     2075   Diesel  145  52.3   

       engineSize  
0             1.8  
1             2.1  
2             5.5  
3             4.0  
4             4.0  
...           ...  
13114         2.0  
13115         2.0  
13116         2.1  
13117         2.0  
13118         2.9  

[13119 rows x 9 columns]

In [119]:
df.head()
#top 5 recordss

model  year  price transmission  mileage fuelType  tax   mpg  \
0        SLK  2005   5200    Automatic    63000   Petrol  325  32.1   
1    S Class  2017  34948    Automatic    27000   Hybrid   20  61.4   
2   SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0   
3    G Class  2016  61948    Automatic    16000   Petrol  325  30.4   
4    G Class  2016  73948    Automatic     4000   Petrol  325  30.1   

   engineSize  
0         1.8  
1         2.1  
2         5.5  
3         4.0  
4         4.0

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13119 entries, 0 to 13118
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         13119 non-null  object 
 1   year          13119 non-null  int64  
 2   price         13119 non-null  int64  
 3   transmission  13119 non-null  object 
 4   mileage       13119 non-null  int64  
 5   fuelType      13119 non-null  object 
 6   tax           13119 non-null  int64  
 7   mpg           13119 non-null  float64
 8   engineSize    13119 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 922.6+ KB


In [121]:
df.describe()

year          price        mileage           tax           mpg  \
count  13119.000000   13119.000000   13119.000000  13119.000000  13119.000000   
mean    2017.296288   24698.596920   21949.559037    129.972178     55.155843   
std        2.224709   11842.675542   21176.512267     65.260286     15.220082   
min     1970.000000     650.000000       1.000000      0.000000      1.100000   
25%     2016.000000   17450.000000    6097.500000    125.000000     45.600000   
50%     2018.000000   22480.000000   15189.000000    145.000000     56.500000   
75%     2019.000000   28980.000000   31779.500000    145.000000     64.200000   
max     2020.000000  159999.000000  259000.000000    580.000000    217.300000   

         engineSize  
count  13119.000000  
mean       2.071530  
std        0.572426  
min        0.000000  
25%        1.800000  
50%        2.000000  
75%        2.100000  
max        6.200000

In [114]:
df_test = pd.read_csv('test1.csv')

In [115]:
df_test

Unnamed: 0  Column1  Column2  Column3  Column4
0       Row1        0        1        2        3
1       Row2        4        5        6        7
2       Row3        8        9       10       11
3       Row4       12       13       14       15
4       Row5       16       17       18       19

In [122]:
df['mileage'].value_counts()

1000     324
16        62
3999      61
2000      59
9         45
        ... 
13250      1
31870      1
21055      1
10537      1
2426       1
Name: mileage, Length: 9716, dtype: int64

In [125]:
df[df['price']>100000]

model  year   price transmission  mileage fuelType  tax   mpg  \
5       SL CLASS  2011  149948    Automatic     3000   Petrol  570  21.4   
8        G Class  2019  139948    Automatic    12000   Petrol  145  21.4   
1011     A Class  2019  104999    Semi-Auto     5822   Petrol  150  22.6   
1980     S Class  2019  109995    Semi-Auto     4688   Petrol  150  31.7   
2629     A Class  2019  123846    Semi-Auto     2951   Petrol  145  22.1   
2647     A Class  2019  125796    Automatic      637   Petrol  145  24.8   
3978     G Class  2019  102502    Semi-Auto     8691   Diesel  150  11.0   
4087     S Class  2019  104590    Automatic     3671   Petrol  145  31.7   
4094     A Class  2019  124366    Semi-Auto      880   Petrol  145  24.8   
4209     S Class  2018  104400    Semi-Auto     3796   Petrol  145  31.7   
4759     A Class  2019  126000    Automatic      250   Petrol  145  24.6   
5311     A Class  2019  105000    Semi-Auto     6807   Petrol  150  22.6   
5902     G Class  2018  135771    Semi-Auto    19000   Petrol  145  21.4   
6199     G Class  2020  159999    Semi-Auto     1350   Petrol  145  21.4   
6210     A Class  2019  129990    Automatic     1000   Petrol  145  24.8   
6223     S Class  2019  124999    Automatic     1500   Petrol  145  31.7   
6386     G Class  2018  139995    Semi-Auto    13046   Petrol  145  21.4   
7134     A Class  2019  115359    Semi-Auto     1000   Petrol  145  30.1   
7828     A Class  2019  109445    Automatic      195   Petrol  145  22.6   
7864     G Class  2018  135124    Semi-Auto    18234   Petrol  150  21.4   
8673     A Class  2019  134219    Semi-Auto     1000   Petrol  145  24.8   
8737     A Class  2019  140319    Semi-Auto      785   Petrol  150  22.1   
8745     A Class  2018  109989    Semi-Auto     2122   Petrol  145  24.8   
8821     A Class  2020  138439    Semi-Auto     1000   Petrol  145  22.1   
9133     A Class  2019  139559    Semi-Auto     1000   Petrol  145  22.1   
9159     A Class  2019  114199    Semi-Auto      891   Petrol  145  22.6   
9241     A Class  2017  100124    Automatic      439   Petrol  145  24.8   
10044    G Class  2020  154998    Automatic     3000   Petrol  150  21.4   
13060    A Class  2017  109495    Automatic     1755   Petrol  145  24.8   

       engineSize  
5             6.2  
8             4.0  
1011          4.0  
1980          4.0  
2629          4.0  
2647          4.0  
3978          3.0  
4087          4.0  
4094          4.0  
4209          4.0  
4759          4.0  
5311          4.0  
5902          4.0  
6199          4.0  
6210          4.0  
6223          4.0  
6386          4.0  
7134          4.0  
7828          4.0  
7864          4.0  
8673          4.0  
8737          4.0  
8745          4.0  
8821          4.0  
9133          4.0  
9159          4.0  
9241          4.0  
10044         4.0  
13060         4.0

CELL


In [128]:
#csv
from io import StringIO, BytesIO

In [129]:
data = ('col1,col2,col3\n'
       'x,y,1\n'
       'a,b,2\n'
       'c,d,3\n')

In [130]:
type(data)

str

In [131]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [132]:
#read the specific columns
df = pd.read_csv(StringIO(data), usecols= ['col1','col3'])

In [133]:
df

col1  col3
0    x     1
1    a     2
2    c     3

In [134]:
df.to_csv('test2.csv')

In [137]:
data = ('index,a,b,c\n'
       '4,apple,bat,6.7\n'
       '8,orange,cow,11')

In [139]:
pd.read_csv(StringIO(data),index_col = 0)

a    b     c
index                   
4       apple  bat   6.7
8      orange  cow  11.0

In [149]:
data = ('a,b,c\n'
       '4,apple,bat\n'
       '8,orange,cow')

In [150]:
pd.read_csv(StringIO(data))

a       b    c
0  4   apple  bat
1  8  orange  cow

In [146]:
pd.read_csv(StringIO(data),index_col=False)

/var/folders/cj/vq6gk8g5479_t1z1n10mbbn00000gn/T/ipykernel_76093/264139308.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  pd.read_csv(StringIO(data),index_col=False)


a       b    c
0  4   apple  bat
1  8  orange  cow

In [151]:
data = ('a,b,c\n'
       '4,apple,bat\n'
       '8,orange,cow')

In [152]:
pd.read_csv(StringIO(data),usecols = ['b','c'], index_col=False)
#combining usecols and index cols

b    c
0   apple  bat
1  orange  cow

In [153]:
##quoting and escape characters (NLP useful)
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [154]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  hello, "Bob", nice to see you  5

In [162]:
#URL to CSV
url = 'https://download.bls.gov/pub/time.series/cu/cu.item'
df = pd.read_csv(url, sep='\t')

HTTPError: HTTP Error 403: Forbidden

In [163]:
df.head()

col1  col3
0    x     1
1    a     2
2    c     3

In [1]:
##read json to csv


In [2]:


data = '{"employee_name" : "james", "email": "james@gmail.com", "job_profile": [{"title1":"team Lead","title2":"Sr. developer"}]}'
df1 = pd.read_json(data)



In [3]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header = None)

In [4]:
df.head()
#only key and value pair here

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [5]:
#convert json to csv


In [6]:
df.to_csv('wine.csv')

In [7]:
#convert json to differnt json format
df.to_json(orient = "records")

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"

In [8]:
df1.to_json()

'{"employee_name":{"0":"james"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"team Lead","title2":"Sr. developer"}}}'

In [9]:
df1.to_json(orient = "records")

'[{"employee_name":"james","email":"james@gmail.com","job_profile":{"title1":"team Lead","title2":"Sr. developer"}}]'

In [10]:
#reading html content


In [13]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'
dfs = pd.read_html(url)

In [14]:
dfs[0]

Bank NameBank       CityCity StateSt  CertCert  \
0             Heartland Tri-State Bank        Elkhart      KS     25851   
1                  First Republic Bank  San Francisco      CA     59017   
2                       Signature Bank       New York      NY     57053   
3                  Silicon Valley Bank    Santa Clara      CA     24735   
4                    Almena State Bank         Almena      KS     15426   
..                                 ...            ...     ...       ...   
562                 Superior Bank, FSB       Hinsdale      IL     32646   
563                Malta National Bank          Malta      OH      6629   
564    First Alliance Bank & Trust Co.     Manchester      NH     34264   
565  National State Bank of Metropolis     Metropolis      IL      3815   
566                   Bank of Honolulu       Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0                 Dream First Bank, N.A.       July 28, 2023     10544  
1              JPMorgan Chase Bank, N.A.         May 1, 2023     10543  
2                    Flagstar Bank, N.A.      March 12, 2023     10540  
3    First–Citizens Bank & Trust Company      March 10, 2023     10539  
4                            Equity Bank    October 23, 2020     10538  
..                                   ...                 ...       ...  
562                Superior Federal, FSB       July 27, 2001      6004  
563                    North Valley Bank         May 3, 2001      4648  
564  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
565              Banterra Bank of Marion   December 14, 2000      4646  
566                   Bank of the Orient    October 13, 2000      4645  

[567 rows x 7 columns]

In [15]:
type(dfs)

list

In [16]:
dfs

[                         Bank NameBank       CityCity StateSt  CertCert  \
 0             Heartland Tri-State Bank        Elkhart      KS     25851   
 1                  First Republic Bank  San Francisco      CA     59017   
 2                       Signature Bank       New York      NY     57053   
 3                  Silicon Valley Bank    Santa Clara      CA     24735   
 4                    Almena State Bank         Almena      KS     15426   
 ..                                 ...            ...     ...       ...   
 562                 Superior Bank, FSB       Hinsdale      IL     32646   
 563                Malta National Bank          Malta      OH      6629   
 564    First Alliance Bank & Trust Co.     Manchester      NH     34264   
 565  National State Bank of Metropolis     Metropolis      IL      3815   
 566                   Bank of Honolulu       Honolulu      HI     21029   
 
                  Acquiring InstitutionAI Closing DateClosing  FundFund  
 0          

In [19]:
url1 = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs1 = pd.read_html(url1, match = 'Country', header = 0)

In [22]:
dfs1[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

In [23]:
#reading excel files


In [24]:
df_excel = pd.read_excel('')

FileNotFoundError: [Errno 2] No such file or directory: 'Excel_Sample.xlsx'

In [25]:
#pickling
