In [1]:
#pip install numpy

#anaconda -> conda install numpy
#numpy


In [2]:
#importing numpy
import numpy as np

In [3]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape

(5,)

In [9]:
#multidimensional array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,5,6,8]

arr = np.array([my_lst1, my_lst2, my_lst3])

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 6, 8]])

In [11]:
arr.shape

(3, 5)

In [17]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 5, 6, 8]])

In [18]:
arr.shape

(3, 5)

In [19]:
#indexing


In [40]:
#accesing the array element
arr = np.array([1,2,3,4,5,6,7,8,9])

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[3]

4

In [24]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,5,6,8]
arr = np.array([my_lst1, my_lst2, my_lst3])

In [25]:
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 6, 8]])

In [26]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 6, 8]])

In [27]:
arr[1,2]

4

In [28]:
arr[0:1,0:1]

array([[1]])

In [29]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [31]:
arr[1:,3:]

array([[5, 6],
       [6, 8]])

In [32]:
arr[1:,2:4]

array([[4, 5],
       [5, 6]])

In [33]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [36]:
arr = np.arange(0,10,step=2)

In [37]:
arr

array([0, 2, 4, 6, 8])

In [39]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [46]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [44]:
arr1 = arr
arr1[3:]=500

In [45]:
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [47]:
print(arr)

[  1   2   3 500 500 500 500 500 500]


In [48]:
arr1 = arr.copy()


In [49]:
print(arr)

[  1   2   3 500 500 500 500 500 500]


In [50]:
arr1[3:]=1000
print(arr1)

[   1    2    3 1000 1000 1000 1000 1000 1000]


In [51]:
val = 2
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [52]:
arr*2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [53]:
arr/2

array([  0.5,   1. ,   1.5, 250. , 250. , 250. , 250. , 250. , 250. ])

In [54]:
arr%2

array([1, 0, 1, 0, 0, 0, 0, 0, 0])

In [55]:
arr+100

array([101, 102, 103, 600, 600, 600, 600, 600, 600])

In [56]:
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [57]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [58]:
arr[arr<20]

array([1, 2, 3])

In [59]:
np.ones(4)

array([1., 1., 1., 1.])

In [60]:
np.ones((2,5),dtype =int)
#two rows and 5 col of ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [68]:
#random distribution
np.random.rand(5,5)

array([[0.51664222, 0.50434313, 0.61452602, 0.44336184, 0.85786822],
       [0.05316072, 0.43625461, 0.06781426, 0.89979073, 0.77279681],
       [0.07530974, 0.46327257, 0.58815401, 0.56880643, 0.40346843],
       [0.37703251, 0.72847346, 0.43396913, 0.11117976, 0.47647319],
       [0.221295  , 0.0582119 , 0.273297  , 0.52061836, 0.27114634]])

In [74]:
np.random.randint(0,100,20).reshape(5,4)

array([[55, 19, 77, 17],
       [53, 69, 93, 82],
       [53, 56, 34, 79],
       [36, 97, 51, 24],
       [79, 81, 92, 54]])

In [79]:
#pandas
import pandas as pd
import numpy as np

In [83]:
#playing with data frame

df = pd.DataFrame(np.arange(0,20).reshape(5,4),index = ['Row1','Row2','Row3','Row4','Row5'],columns = ["Column1","Column2","Column3","Column4"])
                                                        
                                                        

In [84]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [85]:
df.to_csv('Test1.csv')
#make a csv file 

In [88]:
#accessing the elements
# 1 -> .loc(row index only) 2->> .iloc(index location)-(both row and column index)
type(df.loc['Row1'])


pandas.core.series.Series

In [93]:
type(df.iloc[:,:])

pandas.core.frame.DataFrame

In [94]:
df.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [95]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [98]:
#convert data frame to arrays
df.iloc[:,:].values.shape

(5, 4)

In [100]:
df['Column1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Column1, dtype: int64

In [101]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [102]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [105]:
df[['Column3','Column4']]

Column3  Column4
Row1        2        3
Row2        6        7
Row3       10       11
Row4       14       15
Row5       18       19

In [117]:
df = pd.read_csv('mercedesbenz.csv')

In [118]:
df

model  year  price transmission  mileage fuelType  tax   mpg  \
0             SLK  2005   5200    Automatic    63000   Petrol  325  32.1   
1         S Class  2017  34948    Automatic    27000   Hybrid   20  61.4   
2        SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0   
3         G Class  2016  61948    Automatic    16000   Petrol  325  30.4   
4         G Class  2016  73948    Automatic     4000   Petrol  325  30.1   
...           ...   ...    ...          ...      ...      ...  ...   ...   
13114     C Class  2020  35999    Automatic      500   Diesel  145  55.4   
13115     B Class  2020  24699    Automatic     2500   Diesel  145  55.4   
13116   GLC Class  2019  30999    Automatic    11612   Diesel  145  41.5   
13117   CLS Class  2019  37990    Automatic     2426   Diesel  145  45.6   
13118     S Class  2019  54999    Automatic     2075   Diesel  145  52.3   

       engineSize  
0             1.8  
1             2.1  
2             5.5  
3             4.0  
4             4.0  
...           ...  
13114         2.0  
13115         2.0  
13116         2.1  
13117         2.0  
13118         2.9  

[13119 rows x 9 columns]

In [119]:
df.head()
#top 5 recordss

model  year  price transmission  mileage fuelType  tax   mpg  \
0        SLK  2005   5200    Automatic    63000   Petrol  325  32.1   
1    S Class  2017  34948    Automatic    27000   Hybrid   20  61.4   
2   SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0   
3    G Class  2016  61948    Automatic    16000   Petrol  325  30.4   
4    G Class  2016  73948    Automatic     4000   Petrol  325  30.1   

   engineSize  
0         1.8  
1         2.1  
2         5.5  
3         4.0  
4         4.0

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13119 entries, 0 to 13118
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         13119 non-null  object 
 1   year          13119 non-null  int64  
 2   price         13119 non-null  int64  
 3   transmission  13119 non-null  object 
 4   mileage       13119 non-null  int64  
 5   fuelType      13119 non-null  object 
 6   tax           13119 non-null  int64  
 7   mpg           13119 non-null  float64
 8   engineSize    13119 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 922.6+ KB


In [121]:
df.describe()

year          price        mileage           tax           mpg  \
count  13119.000000   13119.000000   13119.000000  13119.000000  13119.000000   
mean    2017.296288   24698.596920   21949.559037    129.972178     55.155843   
std        2.224709   11842.675542   21176.512267     65.260286     15.220082   
min     1970.000000     650.000000       1.000000      0.000000      1.100000   
25%     2016.000000   17450.000000    6097.500000    125.000000     45.600000   
50%     2018.000000   22480.000000   15189.000000    145.000000     56.500000   
75%     2019.000000   28980.000000   31779.500000    145.000000     64.200000   
max     2020.000000  159999.000000  259000.000000    580.000000    217.300000   

         engineSize  
count  13119.000000  
mean       2.071530  
std        0.572426  
min        0.000000  
25%        1.800000  
50%        2.000000  
75%        2.100000  
max        6.200000

In [114]:
df_test = pd.read_csv('test1.csv')

In [115]:
df_test

Unnamed: 0  Column1  Column2  Column3  Column4
0       Row1        0        1        2        3
1       Row2        4        5        6        7
2       Row3        8        9       10       11
3       Row4       12       13       14       15
4       Row5       16       17       18       19

In [122]:
df['mileage'].value_counts()

1000     324
16        62
3999      61
2000      59
9         45
        ... 
13250      1
31870      1
21055      1
10537      1
2426       1
Name: mileage, Length: 9716, dtype: int64

In [125]:
df[df['price']>100000]

model  year   price transmission  mileage fuelType  tax   mpg  \
5       SL CLASS  2011  149948    Automatic     3000   Petrol  570  21.4   
8        G Class  2019  139948    Automatic    12000   Petrol  145  21.4   
1011     A Class  2019  104999    Semi-Auto     5822   Petrol  150  22.6   
1980     S Class  2019  109995    Semi-Auto     4688   Petrol  150  31.7   
2629     A Class  2019  123846    Semi-Auto     2951   Petrol  145  22.1   
2647     A Class  2019  125796    Automatic      637   Petrol  145  24.8   
3978     G Class  2019  102502    Semi-Auto     8691   Diesel  150  11.0   
4087     S Class  2019  104590    Automatic     3671   Petrol  145  31.7   
4094     A Class  2019  124366    Semi-Auto      880   Petrol  145  24.8   
4209     S Class  2018  104400    Semi-Auto     3796   Petrol  145  31.7   
4759     A Class  2019  126000    Automatic      250   Petrol  145  24.6   
5311     A Class  2019  105000    Semi-Auto     6807   Petrol  150  22.6   
5902     G Class  2018  135771    Semi-Auto    19000   Petrol  145  21.4   
6199     G Class  2020  159999    Semi-Auto     1350   Petrol  145  21.4   
6210     A Class  2019  129990    Automatic     1000   Petrol  145  24.8   
6223     S Class  2019  124999    Automatic     1500   Petrol  145  31.7   
6386     G Class  2018  139995    Semi-Auto    13046   Petrol  145  21.4   
7134     A Class  2019  115359    Semi-Auto     1000   Petrol  145  30.1   
7828     A Class  2019  109445    Automatic      195   Petrol  145  22.6   
7864     G Class  2018  135124    Semi-Auto    18234   Petrol  150  21.4   
8673     A Class  2019  134219    Semi-Auto     1000   Petrol  145  24.8   
8737     A Class  2019  140319    Semi-Auto      785   Petrol  150  22.1   
8745     A Class  2018  109989    Semi-Auto     2122   Petrol  145  24.8   
8821     A Class  2020  138439    Semi-Auto     1000   Petrol  145  22.1   
9133     A Class  2019  139559    Semi-Auto     1000   Petrol  145  22.1   
9159     A Class  2019  114199    Semi-Auto      891   Petrol  145  22.6   
9241     A Class  2017  100124    Automatic      439   Petrol  145  24.8   
10044    G Class  2020  154998    Automatic     3000   Petrol  150  21.4   
13060    A Class  2017  109495    Automatic     1755   Petrol  145  24.8   

       engineSize  
5             6.2  
8             4.0  
1011          4.0  
1980          4.0  
2629          4.0  
2647          4.0  
3978          3.0  
4087          4.0  
4094          4.0  
4209          4.0  
4759          4.0  
5311          4.0  
5902          4.0  
6199          4.0  
6210          4.0  
6223          4.0  
6386          4.0  
7134          4.0  
7828          4.0  
7864          4.0  
8673          4.0  
8737          4.0  
8745          4.0  
8821          4.0  
9133          4.0  
9159          4.0  
9241          4.0  
10044         4.0  
13060         4.0

CELL


In [128]:
#csv
from io import StringIO, BytesIO

In [129]:
data = ('col1,col2,col3\n'
       'x,y,1\n'
       'a,b,2\n'
       'c,d,3\n')

In [130]:
type(data)

str

In [131]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [132]:
#read the specific columns
df = pd.read_csv(StringIO(data), usecols= ['col1','col3'])

In [133]:
df

col1  col3
0    x     1
1    a     2
2    c     3

In [134]:
df.to_csv('test2.csv')

In [137]:
data = ('index,a,b,c\n'
       '4,apple,bat,6.7\n'
       '8,orange,cow,11')

In [139]:
pd.read_csv(StringIO(data),index_col = 0)

a    b     c
index                   
4       apple  bat   6.7
8      orange  cow  11.0

In [149]:
data = ('a,b,c\n'
       '4,apple,bat\n'
       '8,orange,cow')

In [150]:
pd.read_csv(StringIO(data))

a       b    c
0  4   apple  bat
1  8  orange  cow

In [146]:
pd.read_csv(StringIO(data),index_col=False)

/var/folders/cj/vq6gk8g5479_t1z1n10mbbn00000gn/T/ipykernel_76093/264139308.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  pd.read_csv(StringIO(data),index_col=False)


a       b    c
0  4   apple  bat
1  8  orange  cow

In [151]:
data = ('a,b,c\n'
       '4,apple,bat\n'
       '8,orange,cow')

In [152]:
pd.read_csv(StringIO(data),usecols = ['b','c'], index_col=False)
#combining usecols and index cols

b    c
0   apple  bat
1  orange  cow

In [153]:
##quoting and escape characters (NLP useful)
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [154]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  hello, "Bob", nice to see you  5

In [162]:
#URL to CSV
url = 'https://download.bls.gov/pub/time.series/cu/cu.item'
df = pd.read_csv(url, sep='\t')

HTTPError: HTTP Error 403: Forbidden

In [163]:
df.head()

col1  col3
0    x     1
1    a     2
2    c     3

In [ ]:
##read json to csv